# docker build -t web-base -f Dockerfile.base .
FROM ubuntu:17.10

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install nginx

EXPOSE 80

# Webコンテンツの配置
ONBUILD ADD website.tar /var/www/html/

CMD ["nginx", "-g", "daemon off;"]